import Axios from "axios";

export function Pokemon(location) {
    const pokemonRoutes = new Map();
    pokemonRoutes.set('Route 101', ["poochyena@45", "zigzagoon@10", "wurmple@45"])
    pokemonRoutes.set('Route 103', ["poochyena@60", "zigzagoon@20", "wingull@20"])
    pokemonRoutes.set('Route 103 - Surfing', ["tentacool@60", "wingull@35", "pelipper@5"])
    pokemonRoutes.set('Route 102', ["poochyena@20", "zigzagoon@15", "wurmple@20", "seedot@1", "ralts@4", "lotad@17", "kirlia@2", "gardevoir@1", "surskit@19", "masquerain@1"])
    pokemonRoutes.set('Petalburg Woods', ["poochyena@30", "wurmple@25", "silcoon@9", "cascoon@9", "taillow@5", "shroomish@10", "slakoth@5", "breloom@1", "vigoroth@3", "slaking@1", "dustox@1", "beautifly@1"])
    pokemonRoutes.set('Route 104', ["marill@20", "poochyena@40", "wurmple@20", "taillow@10", "wingull@10"])
    pokemonRoutes.set('Route 105', ["tentacool@35", "wingull@15", "pelipper@5", "magikarp@35", "wailmer@10"])
    pokemonRoutes.set('Route 106', ["tentacool@35", "wingull@15", "pelipper@5", "magikarp@35", "wailmer@10"])
    pokemonRoutes.set('Route 107', ["tentacool@20", "wingull@15", "pelipper@5", "magikarp@20", "wailmer@10", "chinchou@10", "lanturn@5", "clamperl@10", "relicanth@5"])
    pokemonRoutes.set('Route 108', ["tentacool@35", "wingull@15", "pelipper@5", "magikarp@35", "wailmer@10"])
    pokemonRoutes.set('Route 109', ["tentacool@35", "wingull@15", "pelipper@5", "magikarp@35", "wailmer@10"])
    pokemonRoutes.set('Abandoned Ship', ["tentacool@48", "tentacruel@4", "magikarp@48"])
    pokemonRoutes.set('Route 115', ["jigglypuff@10", "taillow@34", "swellow@10", "wingull@10", "swablu@30", "igglybuff@5", "wigglytuff@1"])
    pokemonRoutes.set('Meteor Falls', ["zubat@34", "lunatone@15", "solrock@15", "golbat@20", "bagon@10", "shelgon@5", "salamence@1"])
    pokemonRoutes.set('Route 114', ["lotad@30", "lombre@15", "nuzleaf@9", "swablu@20", "seviper@10", "ludicolo@5", "shiftry@1", "zangoose@10"])
    pokemonRoutes.set('Route 113', ["slugma@25", "skarmory@5", "spinda@65", "magcargo@5"])
    pokemonRoutes.set('Route 111', ["sandshrew@31", "trapinch@20", "cacnea@5", "baltoy@24", "sandslash@1", "vibrava@5", "flygon@1", "cacturne@1", "lileep@5", "anorith@5", "cradily@1", "armaldo@1"])
    pokemonRoutes.set('Route 112', ["marill@25", "numel@75"])
    pokemonRoutes.set('Route 116', ["abra@11", "poochyena@25", "taillow@20", "nincada@20", "whismur@17", "skitty@2", "kadabra@1", "alakazam@1", "delcatty@1", "ninjask@1", "shedinja@1"])
    pokemonRoutes.set('Route 117', ["oddish@29", "poochyena@30", "marill@10", "seedot@1", "volbeat@1", "illumise@18", "corphish@10", "crawdaunt@1"])
    pokemonRoutes.set('Rusturf Tunnel', ["whismur@100"])
    pokemonRoutes.set('Route 110', ["oddish@10", "poochyena@20", "wingull@8", "electrike@29", "plusle@2", "minun@15", "gulpin@15", "swalot@1"])
    pokemonRoutes.set('Route 118', ["zigzagoon@25", "linoone@10", "wingull@19", "electrike@25", "manectric@10", "kecleon@1", "carvanha@10"])
    pokemonRoutes.set('Route 119', ["oddish@28", "zigzagoon@25", "linoone@25", "kecleon@1", "tropius@9", "carvanha@10", "feebas@1", "milotic@1"])
    pokemonRoutes.set('Route 120', ["oddish@25", "marill@15", "poochyena@20", "mightyena@29", "seedot@1", "kecleon@1", "absol@8", "azumarill@1"])
    pokemonRoutes.set('Route 121', ["oddish@15", "gloom@5", "poochyena@20", "mightyena@20", "wingull@9", "kecleon@1", "shuppet@30"])
    pokemonRoutes.set('Route 122', ["wingull@35", "tentacool@60", "pelipper@5"])
    pokemonRoutes.set('Route 123', ["oddish@15", "gloom@4", "poochyena@20", "mightyena@20", "wingull@9", "kecleon@1", "shuppet@29", "vileplume@1", "bellossom@1"])
    pokemonRoutes.set('Route 124', ["tentacool@15", "wingull@15", "pelipper@5", "sharpedo@5", "wailmer@10", "magikarp@20", "chinchou@10", "clamperl@14", "relicanth@5", "gorebyss@1"])
    pokemonRoutes.set('Route 125', ["tentacool@20", "wingull@20", "pelipper@5", "magikarp@30", "wailmer@10", "sharpedo@5", "tentacruel@5", "gyarados@5"])
    pokemonRoutes.set('Route 126', ["tentacool@15", "wingull@15", "pelipper@5", "sharpedo@5", "wailmer@10", "magikarp@20", "chinchou@10", "clamperl@14", "relicanth@5", "huntail@1"])
    pokemonRoutes.set('Route 127', ["tentacool@20", "wingull@20", "pelipper@5", "magikarp@30", "wailmer@10", "sharpedo@5", "tentacruel@5", "wailord@5"])
    pokemonRoutes.set('Route 128', ["tentacool@25", "wingull@10", "pelipper@5", "magikarp@25", "wailmer@10", "luvdisc@15", "corsola@10"])
    pokemonRoutes.set('Seafloor Cavern', ["zubat@20", "golbat@5", "tentacool@20", "magikarp@25", "wailmer@20", "tentacruel@5", "graveler@5"])
    pokemonRoutes.set('Route 129', ["tentacool@25", "wingull@15", "pelipper@5", "magikarp@30", "wailmer@15", "wailord@5", "sharpedo@5"])
    pokemonRoutes.set('Route 130', ["tentacool@20", "wingull@14", "pelipper@5", "magikarp@20", "wailmer@10", "sharpedo@5", "wynaut@1", "horsea@15", "seadra@4", "wobbuffet@1", "tentacruel@5"])
    pokemonRoutes.set('Route 131', ["tentacool@20", "wingull@15", "pelipper@5", "magikarp@20", "wailmer@10", "sharpedo@5", "horsea@15", "seadra@5", "tentacruel@5"])
    pokemonRoutes.set('Sky Pillar', ["golbat@20", "sableye@15", "claydol@15", "banette@15", "altaria@10", "mawile@10", "ariados@15",])
    pokemonRoutes.set('Route 132', ["tentacool@20", "wingull@15", "pelipper@5", "magikarp@20", "wailmer@10", "sharpedo@5", "horsea@15", "seadra@5", "tentacruel@5"])
    pokemonRoutes.set('Route 133', ["tentacool@20", "wingull@15", "pelipper@5", "magikarp@20", "wailmer@10", "sharpedo@5", "horsea@15", "seadra@5", "tentacruel@5"])
    pokemonRoutes.set('Route 134', ["tentacool@20", "wingull@15", "pelipper@5", "magikarp@20", "wailmer@10", "sharpedo@5", "horsea@20", "seadra@4", "kingdra@1"])
    pokemonRoutes.set('Fiery Pass', ["machop@12", "grimer@10", "koffing@19", "slugma@10", "numel@24", "torkoal@18", "magcargo@5", "muk@1", "weezing@1"])
    pokemonRoutes.set('Jagged Pass', ["machop@20", "numel@50", "spoink@20", "machoke@4", "machamp@1", "camerupt@4", "grumpig@1"])
    pokemonRoutes.set('Granite Cave', ["zubat@20", "abra@10", "geodude@15", "makuhita@15", "aron@9", "sableye@10", "mawile@10", "nosepass@10", "lairon@1"])
    pokemonRoutes.set('Victory Road', ["zubat@10", "golbat@3", "whismur@9", "loudred@3", "makuhita@10", "hariyama@1", "aron@10", "lairon@3", "mawile@9", "meditite@10", "medicham@3", "geodude@8", "graveler@2", "aggron@1", "goldeen@5", "barboach@9", "whiscash@1", "exploud@1", "golem@1", "crobat@1"])
    pokemonRoutes.set('Safari Zone', ["oddish@4", "geodude@4", "goldeen@4", "hoothoot@4", "ledyba@4", "spinarak@4", "wooper@4", "mareep@4", "sunkern@4", "pikachu@1", "psyduck@4", "doduo@4", "natu@4", "marill@4", "pineco@4", "snubbull@4",
        "shuckle@2", "remoraid@3", "gloom@1", "rhyhorn@1", "teddiursa@3", "houndour@3", "phanpy@3", "quagsire@1", "golduck@1", "xatu@1", "octillery@1", "seaking@1", "girafarig@1", "gligar@2", "dodrio@1", "pinsir@1",
        "aipom@4", "heracross@1", "stantler@2", "miltank@2", "pichu@1", "raichu@1", "donphan@1", "rhydon@1"])
    pokemonRoutes.set('New Mauville', ["magnemite@49", "magneton@5", "voltorb@49", "electrode@5"])
    pokemonRoutes.set('Weather Institute', ["castform@100"])
    pokemonRoutes.set('Lilycove City', ["tentacool@30", "wingull@15", "pelipper@5", "magikarp@29", "wailmer@10", "staryu@10", "starmie@1"])
    pokemonRoutes.set('Mt. Pyre', ["shuppet@25", "duskull@25", "chimecho@10", "vulpix@14", "wingull@10", "meditite@14", "dusclops@1", "ninetales@1"])
    pokemonRoutes.set('Shoal Cave', ["zubat@20", "golbat@10", "spheal@23", "tentacool@10", "magikarp@10", "wailmer@10", "snorunt@10", "glalie@1", "sealeo@5", "walrein@1"])
    pokemonRoutes.set('Mossdeep City', ["beldum@94", "metang@5", "metagross@1"])
    pokemonRoutes.set('Legendary Island', ["regirock@10", "regice@10", "registeel@10", "latias@10", "latios@10", "kyogre@10", "groudon@10", "rayquaza@10", "jirachi@10", "deoxys@10"])





    if (pokemonRoutes.get(location) == undefined) {
        return null
    }

    var route = pokemonRoutes.get(location);
    var chance = Math.floor(Math.random() * 100) + 1;
    var pokemon;
    var sum = 0;
    for (let i = 0; i < route.length; i++) {
        const temp = route[i].split("@");
        if (chance <= parseInt(temp[1]) + sum) {
            pokemon = temp[0];
            break;
        }
        sum = parseInt([temp[1]]) + sum;
    }
    return pokemon;
    // return "The chances were: " + chance + ". The pokemon was: " + pokemon + "."

}

export function WildMusic() {
    let music = [
        "https://vgmsite.com/soundtracks/pokemon-black-and-white/vpcjshuf/114%20Battle%21%20Wild%20Pokemon.mp3$.5",
        "https://vgmsite.com/soundtracks/pokemon-diamond-and-pearl-super-music-collection/qyrqtktu/1-09%20Battle%21%20Wild%20Pok%C3%A9mon.mp3$.2",
        "https://vgmsite.com/soundtracks/pokemon-ruby-sapphire-music-super-complete/ktnxrati/1-09%20Battle%21%20Wild%20Pok%C3%A9mon.mp3$.4",
        "https://vgmsite.com/soundtracks/pokemon-black-and-white-2-super-music-collection/kdewhncolk/07%20Battle%21%20%28Wild%20Pok%C3%A9mon%29.mp3$.5"
    ]
    return (music[Math.floor(Math.random() * music.length)])
}

export function CheckMirageIsland(n) {
    let name = ["abomasnow",
        "abra",
        "absol",
        "accelgor",
        "aegislash",
        "aerodactyl",
        "aggron",
        "aipom",
        "alakazam",
        "alomomola",
        "altaria",
        "amaura",
        "ambipom",
        "amoonguss",
        "ampharos",
        "anorith",
        "arbok",
        "arcanine",
        "arceus",
        "archen",
        "archeops",
        "ariados",
        "armaldo",
        "aromatisse",
        "aron",
        "articuno",
        "audino",
        "aurorus",
        "avalugg",
        "axew",
        "azelf",
        "azumarill",
        "azurill",
        "bagon",
        "baltoy",
        "banette",
        "barbaracle",
        "barboach",
        "basculin",
        "bastiodon",
        "bayleef",
        "beartic",
        "beautifly",
        "beedrill",
        "beheeyem",
        "beldum",
        "bellossom",
        "bellsprout",
        "bergmite",
        "bibarel",
        "bidoof",
        "binacle",
        "bisharp",
        "blastoise",
        "blaziken",
        "blissey",
        "blitzle",
        "boldore",
        "bonsly",
        "bouffalant",
        "braixen",
        "braviary",
        "breloom",
        "bronzong",
        "bronzor",
        "budew",
        "buizel",
        "bulbasaur",
        "buneary",
        "bunnelby",
        "burmy",
        "butterfree",
        "cacnea",
        "cacturne",
        "camerupt",
        "carbink",
        "carnivine",
        "carracosta",
        "carvanha",
        "cascoon",
        "castform",
        "caterpie",
        "celebi",
        "chandelure",
        "chansey",
        "charizard",
        "charmander",
        "charmeleon",
        "chatot",
        "cherrim",
        "cherubi",
        "chesnaught",
        "chespin",
        "chikorita",
        "chimchar",
        "chimecho",
        "chinchou",
        "chingling",
        "cinccino",
        "clamperl",
        "clauncher",
        "clawitzer",
        "claydol",
        "clefable",
        "clefairy",
        "cleffa",
        "cloyster",
        "cobalion",
        "cofagrigus",
        "combee",
        "combusken",
        "conkeldurr",
        "corphish",
        "corsola",
        "cottonee",
        "cradily",
        "cranidos",
        "crawdaunt",
        "cresselia",
        "croagunk",
        "crobat",
        "croconaw",
        "crustle",
        "cryogonal",
        "cubchoo",
        "cubone",
        "cyndaquil",
        "darkrai",
        "darmanitan",
        "darumaka",
        "dedenne",
        "deerling",
        "deino",
        "delcatty",
        "delibird",
        "delphox",
        "deoxys",
        "dewgong",
        "dewott",
        "dialga",
        "diancie",
        "diggersby",
        "diglett",
        "ditto",
        "dodrio",
        "doduo",
        "donphan",
        "doublade",
        "dragalge",
        "dragonair",
        "dragonite",
        "drapion",
        "dratini",
        "drifblim",
        "drifloon",
        "drilbur",
        "drowzee",
        "druddigon",
        "ducklett",
        "dugtrio",
        "dunsparce",
        "duosion",
        "durant",
        "dusclops",
        "dusknoir",
        "duskull",
        "dustox",
        "dwebble",
        "eelektrik",
        "eelektross",
        "eevee",
        "ekans",
        "electabuzz",
        "electivire",
        "electrike",
        "electrode",
        "elekid",
        "elgyem",
        "emboar",
        "emolga",
        "empoleon",
        "entei",
        "escavalier",
        "espeon",
        "espurr",
        "excadrill",
        "exeggcute",
        "exeggutor",
        "exploud",
        "farfetchd",
        "fearow",
        "feebas",
        "fennekin",
        "feraligatr",
        "ferroseed",
        "ferrothorn",
        "finneon",
        "flaaffy",
        "flabébé",
        "flareon",
        "fletchinder",
        "fletchling",
        "floatzel",
        "floette",
        "florges",
        "flygon",
        "foongus",
        "forretress",
        "fraxure",
        "frillish",
        "froakie",
        "frogadier",
        "froslass",
        "furfrou",
        "furret",
        "gabite",
        "gallade",
        "galvantula",
        "garbodor",
        "garchomp",
        "gardevoir",
        "gastly",
        "gastrodon",
        "genesect",
        "gengar",
        "geodude",
        "gible",
        "gigalith",
        "girafarig",
        "giratina",
        "glaceon",
        "glalie",
        "glameow",
        "gligar",
        "gliscor",
        "gloom",
        "gogoat",
        "golbat",
        "goldeen",
        "golduck",
        "golem",
        "golett",
        "golurk",
        "goodra",
        "goomy",
        "gorebyss",
        "gothita",
        "gothitelle",
        "gothorita",
        "gourgeist",
        "granbull",
        "graveler",
        "greninja",
        "grimer",
        "grotle",
        "groudon",
        "grovyle",
        "growlithe",
        "grumpig",
        "gulpin",
        "gurdurr",
        "gyarados",
        "happiny",
        "hariyama",
        "haunter",
        "hawlucha",
        "haxorus",
        "heatmor",
        "heatran",
        "heliolisk",
        "helioptile",
        "heracross",
        "herdier",
        "hippopotas",
        "hippowdon",
        "hitmonchan",
        "hitmonlee",
        "hitmontop",
        "honchkrow",
        "honedge",
        "ho", -"oh",
        "hoopa",
        "hoothoot",
        "hoppip",
        "horsea",
        "houndoom",
        "houndour",
        "huntail",
        "hydreigon",
        "hypno",
        "igglybuff",
        "illumise",
        "infernape",
        "inkay",
        "ivysaur",
        "jellicent",
        "jigglypuff",
        "jirachi",
        "jolteon",
        "joltik",
        "jumpluff",
        "jynx",
        "kabuto",
        "kabutops",
        "kadabra",
        "kakuna",
        "kangaskhan",
        "karrablast",
        "kecleon",
        "keldeo",
        "kingdra",
        "kingler",
        "kirlia",
        "klang",
        "klefki",
        "klink",
        "klinklang",
        "koffing",
        "krabby",
        "kricketot",
        "kricketune",
        "krokorok",
        "krookodile",
        "kyogre",
        "kyurem",
        "lairon",
        "lampent",
        "landorus",
        "lanturn",
        "lapras",
        "larvesta",
        "larvitar",
        "latias",
        "latios",
        "leafeon",
        "leavanny",
        "ledian",
        "ledyba",
        "lickilicky",
        "lickitung",
        "liepard",
        "lileep",
        "lilligant",
        "lillipup",
        "linoone",
        "litleo",
        "litwick",
        "lombre",
        "lopunny",
        "lotad",
        "loudred",
        "lucario",
        "ludicolo",
        "lugia",
        "lumineon",
        "lunatone",
        "luvdisc",
        "luxio",
        "luxray",
        "machamp",
        "machoke",
        "machop",
        "magby",
        "magcargo",
        "magikarp",
        "magmar",
        "magmortar",
        "magnemite",
        "magneton",
        "magnezone",
        "makuhita",
        "malamar",
        "mamoswine",
        "manaphy",
        "mandibuzz",
        "manectric",
        "mankey",
        "mantine",
        "mantyke",
        "maractus",
        "mareep",
        "marill",
        "marowak",
        "marshtomp",
        "masquerain",
        "mawile",
        "medicham",
        "meditite",
        "meganium",
        "meloetta",
        "meowstic",
        "meowth",
        "mesprit",
        "metagross",
        "metang",
        "metapod",
        "mew",
        "mewtwo",
        "mienfoo",
        "mienshao",
        "mightyena",
        "milotic",
        "miltank",
        "mime-jr",
        "minccino",
        "minun",
        "misdreavus",
        "mismagius",
        "moltres",
        "monferno",
        "mothim",
        "mr-mime",
        "mudkip",
        "muk",
        "munchlax",
        "munna",
        "murkrow",
        "musharna",
        "natu",
        "nidoking",
        "nidoqueen",
        "nidoran",
        "nidoran",
        "nidorina",
        "nidorino",
        "nincada",
        "ninetales",
        "ninjask",
        "noctowl",
        "noibat",
        "noivern",
        "nosepass",
        "numel",
        "nuzleaf",
        "octillery",
        "oddish",
        "omanyte",
        "omastar",
        "onix",
        "oshawott",
        "pachirisu",
        "palkia",
        "palpitoad",
        "pancham",
        "pangoro",
        "panpour",
        "pansage",
        "pansear",
        "paras",
        "parasect",
        "patrat",
        "pawniard",
        "pelipper",
        "persian",
        "petilil",
        "phanpy",
        "phantump",
        "phione",
        "pichu",
        "pidgeot",
        "pidgeotto",
        "pidgey",
        "pidove",
        "pignite",
        "pikachu",
        "piloswine",
        "pineco",
        "pinsir",
        "piplup",
        "plusle",
        "politoed",
        "poliwag",
        "poliwhirl",
        "poliwrath",
        "ponyta",
        "poochyena",
        "porygon",
        "porygon2",
        "porygon", -"z",
        "primeape",
        "prinplup",
        "probopass",
        "psyduck",
        "pumpkaboo",
        "pupitar",
        "purrloin",
        "purugly",
        "pyroar",
        "quagsire",
        "quilava",
        "quilladin",
        "qwilfish",
        "raichu",
        "raikou",
        "ralts",
        "rampardos",
        "rapidash",
        "raticate",
        "rattata",
        "rayquaza",
        "regice",
        "regigigas",
        "regirock",
        "registeel",
        "relicanth",
        "remoraid",
        "reshiram",
        "reuniclus",
        "rhydon",
        "rhyhorn",
        "rhyperior",
        "riolu",
        "roggenrola",
        "roselia",
        "roserade",
        "rotom",
        "rufflet",
        "sableye",
        "salamence",
        "samurott",
        "sandile",
        "sandshrew",
        "sandslash",
        "sawk",
        "sawsbuck",
        "scatterbug",
        "sceptile",
        "scizor",
        "scolipede",
        "scrafty",
        "scraggy",
        "scyther",
        "seadra",
        "seaking",
        "sealeo",
        "seedot",
        "seel",
        "seismitoad",
        "sentret",
        "serperior",
        "servine",
        "seviper",
        "sewaddle",
        "sharpedo",
        "shaymin",
        "shedinja",
        "shelgon",
        "shellder",
        "shellos",
        "shelmet",
        "shieldon",
        "shiftry",
        "shinx",
        "shroomish",
        "shuckle",
        "shuppet",
        "sigilyph",
        "silcoon",
        "simipour",
        "simisage",
        "simisear",
        "skarmory",
        "skiddo",
        "skiploom",
        "skitty",
        "skorupi",
        "skrelp",
        "skuntank",
        "slaking",
        "slakoth",
        "sliggoo",
        "slowbro",
        "slowking",
        "slowpoke",
        "slugma",
        "slurpuff",
        "smeargle",
        "smoochum",
        "sneasel",
        "snivy",
        "snorlax",
        "snorunt",
        "snover",
        "snubbull",
        "solosis",
        "solrock",
        "spearow",
        "spewpa",
        "spheal",
        "spinarak",
        "spinda",
        "spiritomb",
        "spoink",
        "spritzee",
        "squirtle",
        "stantler",
        "staraptor",
        "staravia",
        "starly",
        "starmie",
        "staryu",
        "steelix",
        "stoutland",
        "stunfisk",
        "stunky",
        "sudowoodo",
        "suicune",
        "sunflora",
        "sunkern",
        "surskit",
        "swablu",
        "swadloon",
        "swalot",
        "swampert",
        "swanna",
        "swellow",
        "swinub",
        "swirlix",
        "swoobat",
        "sylveon",
        "taillow",
        "talonflame",
        "tangela",
        "tangrowth",
        "tauros",
        "teddiursa",
        "tentacool",
        "tentacruel",
        "tepig",
        "terrakion",
        "throh",
        "thundurus",
        "timburr",
        "tirtouga",
        "togekiss",
        "togepi",
        "togetic",
        "torchic",
        "torkoal",
        "tornadus",
        "torterra",
        "totodile",
        "toxicroak",
        "tranquill",
        "trapinch",
        "treecko",
        "trevenant",
        "tropius",
        "trubbish",
        "turtwig",
        "tympole",
        "tynamo",
        "typhlosion",
        "tyranitar",
        "tyrantrum",
        "tyrogue",
        "tyrunt",
        "umbreon",
        "unfezant",
        "unown",
        "ursaring",
        "uxie",
        "vanillish",
        "vanillite",
        "vanilluxe",
        "vaporeon",
        "venipede",
        "venomoth",
        "venonat",
        "venusaur",
        "vespiquen",
        "vibrava",
        "victini",
        "victreebel",
        "vigoroth",
        "vileplume",
        "virizion",
        "vivillon",
        "volbeat",
        "volcanion",
        "volcarona",
        "voltorb",
        "vullaby",
        "vulpix",
        "wailmer",
        "wailord",
        "walrein",
        "wartortle",
        "watchog",
        "weavile",
        "weedle",
        "weepinbell",
        "weezing",
        "whimsicott",
        "whirlipede",
        "whiscash",
        "whismur",
        "wigglytuff",
        "wingull",
        "wobbuffet",
        "woobat",
        "wooper",
        "wormadam",
        "wurmple",
        "wynaut",
        "xatu",
        "xerneas",
        "yamask",
        "yanma",
        "yanmega",
        "yveltal",
        "zangoose",
        "zapdos",
        "zebstrika",
        "zekrom",
        "zigzagoon",
        "zoroark",
        "zorua",
        "zubat",
        "zweilous",
        "zygarde"]
    return name.find(e => e == n)
}

export function CheckLocation(l) {
    let locations = ["Mt. Chimney", "Sootopolis", "Littleroot Town", "Oldale Town", "Petalburg Town", "Rustboro City", "Fallabor Town", "Lavaridge Town", "Dewford Town", "Slateport City", "Mauville City", "Fortree City", "Pacifidlog Town", "Mossdeep City", "Evergrande City"]
    return locations.find(e => e == l)
}

export function RandomPokemon() {
    let name = ["bulbasaur",
        "ivysaur",
        "venusaur",
        "charmander",
        "charmeleon",
        "charizard",
        "squirtle",
        "wartortle",
        "blastoise",
        "caterpie",
        "metapod",
        "butterfree",
        "weedle",
        "kakuna",
        "beedrill",
        "pidgey",
        "pidgeotto",
        "pidgeot",
        "rattata",
        "raticate",
        "spearow",
        "fearow",
        "ekans",
        "arbok",
        "pikachu",
        "raichu",
        "sandshrew",
        "sandslash",
        "nidoran-f",
        "nidorina",
        "nidoqueen",
        "nidoran-m",
        "nidorino",
        "nidoking",
        "clefairy",
        "clefable",
        "vulpix",
        "ninetales",
        "jigglypuff",
        "wigglytuff",
        "zubat",
        "golbat",
        "oddish",
        "gloom",
        "vileplume",
        "paras",
        "parasect",
        "venonat",
        "venomoth",
        "diglett",
        "dugtrio",
        "meowth",
        "persian",
        "psyduck",
        "golduck",
        "mankey",
        "primeape",
        "growlithe",
        "arcanine",
        "poliwag",
        "poliwhirl",
        "poliwrath",
        "abra",
        "kadabra",
        "alakazam",
        "machop",
        "machoke",
        "machamp",
        "bellsprout",
        "weepinbell",
        "victreebel",
        "tentacool",
        "tentacruel",
        "geodude",
        "graveler",
        "golem",
        "ponyta",
        "rapidash",
        "slowpoke",
        "slowbro",
        "magnemite",
        "magneton",
        "farfetchd",
        "doduo",
        "dodrio",
        "seel",
        "dewgong",
        "grimer",
        "muk",
        "shellder",
        "cloyster",
        "gastly",
        "haunter",
        "gengar",
        "onix",
        "drowzee",
        "hypno",
        "krabby",
        "kingler",
        "voltorb",
        "electrode",
        "exeggcute",
        "exeggutor",
        "cubone",
        "marowak",
        "hitmonlee",
        "hitmonchan",
        "lickitung",
        "koffing",
        "weezing",
        "rhyhorn",
        "rhydon",
        "chansey",
        "tangela",
        "kangaskhan",
        "horsea",
        "seadra",
        "goldeen",
        "seaking",
        "staryu",
        "starmie",
        "mr-mime",
        "scyther",
        "jynx",
        "electabuzz",
        "magmar",
        "pinsir",
        "tauros",
        "magikarp",
        "gyarados",
        "lapras",
        "ditto",
        "eevee",
        "vaporeon",
        "jolteon",
        "flareon",
        "porygon",
        "omanyte",
        "omastar",
        "kabuto",
        "kabutops",
        "aerodactyl",
        "snorlax",
        "articuno",
        "zapdos",
        "moltres",
        "dratini",
        "dragonair",
        "dragonite",
        "mewtwo",
        "mew",
        "chikorita",
        "bayleef",
        "meganium",
        "cyndaquil",
        "quilava",
        "typhlosion",
        "totodile",
        "croconaw",
        "feraligatr",
        "sentret",
        "furret",
        "hoothoot",
        "noctowl",
        "ledyba",
        "ledian",
        "spinarak",
        "ariados",
        "crobat",
        "chinchou",
        "lanturn",
        "pichu",
        "cleffa",
        "igglybuff",
        "togepi",
        "togetic",
        "natu",
        "xatu",
        "mareep",
        "flaaffy",
        "ampharos",
        "bellossom",
        "marill",
        "azumarill",
        "sudowoodo",
        "politoed",
        "hoppip",
        "skiploom",
        "jumpluff",
        "aipom",
        "sunkern",
        "sunflora",
        "yanma",
        "wooper",
        "quagsire",
        "espeon",
        "umbreon",
        "murkrow",
        "slowking",
        "misdreavus",
        "unown",
        "wobbuffet",
        "girafarig",
        "pineco",
        "forretress",
        "dunsparce",
        "gligar",
        "steelix",
        "snubbull",
        "granbull",
        "qwilfish",
        "scizor",
        "shuckle",
        "heracross",
        "sneasel",
        "teddiursa",
        "ursaring",
        "slugma",
        "magcargo",
        "swinub",
        "piloswine",
        "corsola",
        "remoraid",
        "octillery",
        "delibird",
        "mantine",
        "skarmory",
        "houndour",
        "houndoom",
        "kingdra",
        "phanpy",
        "donphan",
        "porygon2",
        "stantler",
        "smeargle",
        "tyrogue",
        "hitmontop",
        "smoochum",
        "elekid",
        "magby",
        "miltank",
        "blissey",
        "raikou",
        "entei",
        "suicune",
        "larvitar",
        "pupitar",
        "tyranitar",
        "lugia",
        "ho", -"oh",
        "celebi",
        "treecko",
        "grovyle",
        "sceptile",
        "torchic",
        "combusken",
        "blaziken",
        "mudkip",
        "marshtomp",
        "swampert",
        "poochyena",
        "mightyena",
        "zigzagoon",
        "linoone",
        "wurmple",
        "silcoon",
        "beautifly",
        "cascoon",
        "dustox",
        "lotad",
        "lombre",
        "ludicolo",
        "seedot",
        "nuzleaf",
        "shiftry",
        "taillow",
        "swellow",
        "wingull",
        "pelipper",
        "ralts",
        "kirlia",
        "gardevoir",
        "surskit",
        "masquerain",
        "shroomish",
        "breloom",
        "slakoth",
        "vigoroth",
        "slaking",
        "nincada",
        "ninjask",
        "shedinja",
        "whismur",
        "loudred",
        "exploud",
        "makuhita",
        "hariyama",
        "azurill",
        "nosepass",
        "skitty",
        "delcatty",
        "sableye",
        "mawile",
        "aron",
        "lairon",
        "aggron",
        "meditite",
        "medicham",
        "electrike",
        "manectric",
        "plusle",
        "minun",
        "volbeat",
        "illumise",
        "roselia",
        "gulpin",
        "swalot",
        "carvanha",
        "sharpedo",
        "wailmer",
        "wailord",
        "numel",
        "camerupt",
        "torkoal",
        "spoink",
        "grumpig",
        "spinda",
        "trapinch",
        "vibrava",
        "flygon",
        "cacnea",
        "cacturne",
        "swablu",
        "altaria",
        "zangoose",
        "seviper",
        "lunatone",
        "solrock",
        "barboach",
        "whiscash",
        "corphish",
        "crawdaunt",
        "baltoy",
        "claydol",
        "lileep",
        "cradily",
        "anorith",
        "armaldo",
        "feebas",
        "milotic",
        "castform",
        "kecleon",
        "shuppet",
        "banette",
        "duskull",
        "dusclops",
        "tropius",
        "chimecho",
        "absol",
        "wynaut",
        "snorunt",
        "glalie",
        "spheal",
        "sealeo",
        "walrein",
        "clamperl",
        "huntail",
        "gorebyss",
        "relicanth",
        "luvdisc",
        "bagon",
        "shelgon",
        "salamence",
        "beldum",
        "metang",
        "metagross",
        "regirock",
        "regice",
        "registeel",
        "latias",
        "latios",
        "kyogre",
        "groudon",
        "rayquaza",
        "jirachi",
        "deoxys",
        "turtwig",
        "grotle",
        "torterra",
        "chimchar",
        "monferno",
        "infernape",
        "piplup",
        "prinplup",
        "empoleon",
        "starly",
        "staravia",
        "staraptor",
        "bidoof",
        "bibarel",
        "kricketot",
        "kricketune",
        "shinx",
        "luxio",
        "luxray",
        "budew",
        "roserade",
        "cranidos",
        "rampardos",
        "shieldon",
        "bastiodon",
        "burmy",
        "wormadam",
        "mothim",
        "combee",
        "vespiquen",
        "pachirisu",
        "buizel",
        "floatzel",
        "cherubi",
        "cherrim",
        "shellos",
        "gastrodon",
        "ambipom",
        "drifloon",
        "drifblim",
        "buneary",
        "lopunny",
        "mismagius",
        "honchkrow",
        "glameow",
        "purugly",
        "chingling",
        "stunky",
        "skuntank",
        "bronzor",
        "bronzong",
        "bonsly",
        "mime-jr",
        "happiny",
        "chatot",
        "spiritomb",
        "gible",
        "gabite",
        "garchomp",
        "munchlax",
        "riolu",
        "lucario",
        "hippopotas",
        "hippowdon",
        "skorupi",
        "drapion",
        "croagunk",
        "toxicroak",
        "carnivine",
        "finneon",
        "lumineon",
        "mantyke",
        "snover",
        "abomasnow",
        "weavile",
        "magnezone",
        "lickilicky",
        "rhyperior",
        "tangrowth",
        "electivire",
        "magmortar",
        "togekiss",
        "yanmega",
        "leafeon",
        "glaceon",
        "gliscor",
        "mamoswine",
        "porygon", -"z",
        "gallade",
        "probopass",
        "dusknoir",
        "froslass",
        "rotom",
        "uxie",
        "mesprit",
        "azelf",
        "dialga",
        "palkia",
        "heatran",
        "regigigas",
        "giratina",
        "cresselia",
        "phione",
        "manaphy",
        "darkrai",
        "shaymin",
        "arceus",
        "victini",
        "snivy",
        "servine",
        "serperior",
        "tepig",
        "pignite",
        "emboar",
        "oshawott",
        "dewott",
        "samurott",
        "patrat",
        "watchog",
        "lillipup",
        "herdier",
        "stoutland",
        "purrloin",
        "liepard",
        "pansage",
        "simisage",
        "pansear",
        "simisear",
        "panpour",
        "simipour",
        "munna",
        "musharna",
        "pidove",
        "tranquill",
        "unfezant",
        "blitzle",
        "zebstrika",
        "roggenrola",
        "boldore",
        "gigalith",
        "woobat",
        "swoobat",
        "drilbur",
        "excadrill",
        "audino",
        "timburr",
        "gurdurr",
        "conkeldurr",
        "tympole",
        "palpitoad",
        "seismitoad",
        "throh",
        "sawk",
        "sewaddle",
        "swadloon",
        "leavanny",
        "venipede",
        "whirlipede",
        "scolipede",
        "cottonee",
        "whimsicott",
        "petilil",
        "lilligant",
        "basculin",
        "sandile",
        "krokorok",
        "krookodile",
        "darumaka",
        "darmanitan",
        "maractus",
        "dwebble",
        "crustle",
        "scraggy",
        "scrafty",
        "sigilyph",
        "yamask",
        "cofagrigus",
        "tirtouga",
        "carracosta",
        "archen",
        "archeops",
        "trubbish",
        "garbodor",
        "zorua",
        "zoroark",
        "minccino",
        "cinccino",
        "gothita",
        "gothorita",
        "gothitelle",
        "solosis",
        "duosion",
        "reuniclus",
        "ducklett",
        "swanna",
        "vanillite",
        "vanillish",
        "vanilluxe",
        "deerling",
        "sawsbuck",
        "emolga",
        "karrablast",
        "escavalier",
        "foongus",
        "amoonguss",
        "frillish",
        "jellicent",
        "alomomola",
        "joltik",
        "galvantula",
        "ferroseed",
        "ferrothorn",
        "klink",
        "klang",
        "klinklang",
        "tynamo",
        "eelektrik",
        "eelektross",
        "elgyem",
        "beheeyem",
        "litwick",
        "lampent",
        "chandelure",
        "axew",
        "fraxure",
        "haxorus",
        "cubchoo",
        "beartic",
        "cryogonal",
        "shelmet",
        "accelgor",
        "stunfisk",
        "mienfoo",
        "mienshao",
        "druddigon",
        "golett",
        "golurk",
        "pawniard",
        "bisharp",
        "bouffalant",
        "rufflet",
        "braviary",
        "vullaby",
        "mandibuzz",
        "heatmor",
        "durant",
        "deino",
        "zweilous",
        "hydreigon",
        "larvesta",
        "volcarona",
        "cobalion",
        "terrakion",
        "virizion",
        "tornadus",
        "thundurus",
        "reshiram",
        "zekrom",
        "landorus",
        "kyurem",
        "keldeo",
        "meloetta",
        "genesect"]
    return name[Math.floor(Math.random() * name.length)]
}

export function getPokedex(i) {
    let pokedex = [
        "treecko",
        "grovyle",
        "sceptile",
        "torchic",
        "combusken",
        "blaziken",
        "mudkip",
        "marshtomp",
        "swampert",
        "poochyena",
        "mightyena",
        "zigzagoon",
        "linoone",
        "wurmple",
        "silcoon",
        "beautifly",
        "cascoon",
        "dustox",
        "lotad",
        "lombre",
        "ludicolo",
        "seedot",
        "nuzleaf",
        "shiftry",
        "taillow",
        "swellow",
        "wingull",
        "pelipper",
        "ralts",
        "kirlia",
        "gardevoir",
        "surskit",
        "masquerain",
        "shroomish",
        "breloom",
        "slakoth",
        "vigoroth",
        "slaking",
        "abra",
        "kadabra",
        "alakazam",
        "nincada",
        "ninjask",
        "shedinja",
        "whismur",
        "loudred",
        "exploud",
        "makuhita",
        "hariyama",
        "goldeen",
        "seaking",
        "magikarp",
        "gyarados",
        "azurill",
        "marill",
        "azumarill",
        "geodude",
        "graveler",
        "golem",
        "nosepass",
        "skitty",
        "delcatty",
        "zubat",
        "golbat",
        "crobat",
        "tentacool",
        "tentacruel",
        "sableye",
        "mawile",
        "aron",
        "lairon",
        "aggron",
        "machop",
        "machoke",
        "machamp",
        "meditite",
        "medicham",
        "electrike",
        "manectric",
        "plusle",
        "minun",
        "magnemite",
        "magneton",
        "voltorb",
        "electrode",
        "volbeat",
        "illumise",
        "oddish",
        "gloom",
        "vileplume",
        "bellossom",
        "doduo",
        "dodrio",
        "roselia",
        "gulpin",
        "swalot",
        "carvanha",
        "sharpedo",
        "wailmer",
        "wailord",
        "numel",
        "camerupt",
        "slugma",
        "magcargo",
        "torkoal",
        "grimer",
        "muk",
        "koffing",
        "weezing",
        "spoink",
        "grumpig",
        "sandshrew",
        "sandslash",
        "spinda",
        "skarmory",
        "trapinch",
        "vibrava",
        "flygon",
        "cacnea",
        "cacturne",
        "swablu",
        "altaria",
        "zangoose",
        "seviper",
        "lunatone",
        "solrock",
        "barboach",
        "whiscash",
        "corphish",
        "crawdaunt",
        "baltoy",
        "claydol",
        "lileep",
        "cradily",
        "anorith",
        "armaldo",
        "igglybuff",
        "jigglypuff",
        "wigglytuff",
        "feebas",
        "milotic",
        "castform",
        "staryu",
        "starmie",
        "kecleon",
        "shuppet",
        "banette",
        "duskull",
        "dusclops",
        "tropius",
        "chimecho",
        "absol",
        "vulpix",
        "ninetales",
        "pichu",
        "pikachu",
        "raichu",
        "psyduck",
        "golduck",
        "wynaut",
        "wobbuffet",
        "natu",
        "xatu",
        "girafarig",
        "phanpy",
        "donphan",
        "pinsir",
        "heracross",
        "rhyhorn",
        "rhydon",
        "snorunt",
        "glalie",
        "spheal",
        "sealeo",
        "walrein",
        "clamperl",
        "huntail",
        "gorebyss",
        "relicanth",
        "corsola",
        "chinchou",
        "lanturn",
        "luvdisc",
        "horsea",
        "seadra",
        "kingdra",
        "bagon",
        "shelgon",
        "salamence",
        "beldum",
        "metang",
        "metagross",
        "regirock",
        "regice",
        "registeel",
        "latias",
        "latios",
        "kyogre",
        "groudon",
        "rayquaza",
        "jirachi",
        "deoxys"]
    let count = i * 18;
    var temp = []
    for (let i = 0; i < 6; i++) {
        let t = <div className="pokeflex">
            <div className="pokegrid"><img className="pokedex-pokemon" alt={pokedex[count]} src={"https://img.pokemondb.net/sprites/black-white/normal/" + pokedex[count] + ".png"} onError={(e) => { e.target.src = require("./pokemon gif/blank.png") }} /></div>
            <div className="pokegrid"><img className="pokedex-pokemon" alt={pokedex[count]} src={"https://img.pokemondb.net/sprites/black-white/normal/" + pokedex[count + 1] + ".png"} onError={(e) => { e.target.src = require("./pokemon gif/blank.png") }} /></div>
            <div className="pokegrid"><img className="pokedex-pokemon" alt={pokedex[count]} src={"https://img.pokemondb.net/sprites/black-white/normal/" + pokedex[count + 2] + ".png"} onError={(e) => { e.target.src = require("./pokemon gif/blank.png") }} /></div>
        </div>
        temp.push(t)
        count = count + 3;
    }
    return temp
}

export function getDescription(poke) {
    const descriptions = new Map()
    descriptions.set("treecko", "It makes its nest in a giant tree in the forest. It ferociously guards against anything nearing its territory. It is said to be the protector of the forest’s trees.")
    descriptions.set("grovyle", "Leaves grow out of this POKéMON’s body. They help obscure a GROVYLE from the eyes of its enemies while it is in a thickly overgrown forest.")
    descriptions.set("sceptile", "In the jungle, its power is without equal. This POKéMON carefully grows trees and plants. It regulates its body temperature by basking in sunlight.")
    descriptions.set("torchic", "If attacked, it strikes back by spitting balls of fire it forms in its stomach. A TORCHIC dislikes darkness because it can’t see its surroundings.")
    descriptions.set("combusken", "It lashes out with 10 kicks per second. Its strong fighting instinct compels it to keep up its offensive until the opponent gives up.")
    descriptions.set("blaziken", "It learns martial arts that use punches and kicks. Every several years, its old feathers burn off, and new, supple feathers grow back in their place.")
    descriptions.set("mudkip", "On land, it can powerfully lift large boulders by planting its four feet and heaving. It sleeps by burying itself in soil at the water’s edge.")
    descriptions.set("marshtomp", "Its toughened hind legs enable it to stand upright. Because it weakens if its skin dries out, it replenishes fluids by playing in mud.")
    descriptions.set("swampert", "If it senses the approach of a storm and a tidal wave, it protects its seaside nest by piling up boulders. It swims as fast as a jet ski.")
    descriptions.set("poochyena", "It savagely threatens foes with bared fangs. It chases after fleeing targets tenaciously. It turns tail and runs, however, if the foe strikes back.")
    descriptions.set("mightyena", "In the wild, MIGHTYENA live in a pack. They never defy their leader’s orders. They defeat foes with perfectly coordinated teamwork.")
    descriptions.set("zigzagoon", "Rubbing its nose against the ground, it always wanders about back and forth in search of something. It is distinguished by the zigzag footprints it leaves.")
    descriptions.set("linoone", "It is exceedingly fast if it only has to run in a straight line. When it spots pond-dwelling prey underwater, it quickly leaps in and catches it with its sharp claws.")
    descriptions.set("wurmple", "It sticks to tree branches and eats leaves. The thread it spits from its mouth, which becomes gooey when it touches air, slows the movement of its foes.")
    descriptions.set("silcoon", "It prepares for evolution using the energy it stored while it was a WURMPLE. It keeps watch over the surroundings with its two eyes.")
    descriptions.set("beautifly", "Its colorfully patterned wings are its most prominent feature. It flies through flower-covered fields collecting pollen. It attacks ferociously when angered.")
    descriptions.set("cascoon", "To avoid detection by its enemies, it hides motionlessly beneath large leaves and in the gaps of branches. It also attaches dead leaves to its body for camouflage.")
    descriptions.set("dustox", "It is a nocturnal POKéMON that flies from fields and mountains to the attraction of streetlights at night. It looses highly toxic powder from its wings.")
    descriptions.set("lotad", "This POKéMON lives in ponds with clean water. It is known to ferry small POKéMON across ponds by carrying them on the broad leaf on its head.")
    descriptions.set("lombre", "In the evening, it takes great delight in popping out of rivers and startling people. It feeds on aquatic moss that grows on rocks in the riverbed.")
    descriptions.set("ludicolo", "When it hears festive music, all the cells in its body become stimulated, and it begins moving in rhythm. It does not quail even when it faces a tough opponent.")
    descriptions.set("seedot", "It hangs off branches and absorbs nutrients. When it finishes eating, its body becomes so heavy that it drops to the ground with a thump.")
    descriptions.set("nuzleaf", "A forest-dwelling POKéMON that is skilled at climbing trees. Its long and pointed nose is its weak point. It loses power if the nose is gripped.")
    descriptions.set("shiftry", "It is said to arrive on chilly, wintry winds. Feared from long ago as the guardian of forests, this POKéMON lives in a deep forest where people do not venture.")
    descriptions.set("taillow", "Although it is small, it is very courageous. It will take on a larger SKARMORY on an equal footing. However, its will weakens if it becomes hungry.")
    descriptions.set("swellow", "A SWELLOW dives upon prey from far above. It never misses its targets. It takes to the skies in search of lands with a warm climate.")
    descriptions.set("wingull", "It makes its nest on a sheer cliff at the edge of the sea. It has trouble keeping its wings flapping in flight. Instead, it soars on updrafts.")
    descriptions.set("pelipper", "It skims the tops of waves as it flies. When it spots prey, it uses its large beak to scoop up the victim with water. It protects its eggs in its beak.")
    descriptions.set("ralts", "A RALTS has the power to sense the emotions of people and POKéMON with the horns on its head. It takes cover if it senses any hostility.")
    descriptions.set("kirlia", "A KIRLIA has the psychic power to create a rip in the dimensions and see into the future. It is said to dance with pleasure on sunny mornings.")
    descriptions.set("gardevoir", "It apparently does not feel the pull of gravity because it supports itself with psychic power. It will give its life to protect its TRAINER.")
    descriptions.set("surskit", "They gather on puddles after evening downpours, gliding across the surface of water as if sliding. It secretes honey with a sweet aroma from its head.")
    descriptions.set("masquerain", "It intimidates foes with the large eyelike patterns on its antennae. Because it can’t fly if its wings get wet, it shelters itself from rain under large trees and eaves.")
    descriptions.set("shroomish", "It loves to eat damp, composted soil in forests. If you enter a forest after a long rain, you can see many SHROOMISH feasting on composted soil.")
    descriptions.set("breloom", "It scatters spores from holes in the cap on its head. It loves warm and humid climates. It feeds on trees and plants in fields and forests.")
    descriptions.set("slakoth", "It sleeps virtually all day and night long. It doesn’t change its nest its entire life, but it sometimes travels great distances by swimming in rivers.")
    descriptions.set("vigoroth", "It can’t keep still because its blood boils with energy. It runs through the fields and mountains all day to calm itself. If it doesn’t, it can’t sleep at night.")
    descriptions.set("slaking", "Hordes of SLAKING gather around trees when fruits come into season. They wait around patiently for ripened fruits to fall out of the trees.")
    descriptions.set("abra", "A POKéMON that sleeps 18 hours a day. Observation revealed that it uses TELEPORT to change its location once every hour.")
    descriptions.set("kadabra", "It is rumored that a boy with psychic abilities suddenly transformed into KADABRA while he was assisting research into extrasensory powers.")
    descriptions.set("alakazam", "While it has strong psychic abilities and high intelligence, an ALAKAZAM’s muscles are very weak. It uses psychic power to move its body.")
    descriptions.set("nincada", "It makes its nest at the roots of a mighty tree. Using its whiskerlike antennae, it probes its surroundings in the pitch-black darkness of soil.")
    descriptions.set("ninjask", "Because it darts about vigorously at high speed, it is very difficult to see. Hearing its distinctive cries for too long induces a headache.")
    descriptions.set("shedinja", "A peculiar POKéMON that floats in air even though its wings remain completely still. The inside of its body is hollow and utterly dark.")
    descriptions.set("whismur", "Its cries equal a jet plane in volume. It inhales through its ear canals. Because of this system, it can cry continually without having to catch its breath.")
    descriptions.set("loudred", "It positions the round speakers on its head to assail foes with ultrasonic waves at massive volume. It builds power by stomping the ground.")
    descriptions.set("exploud", "It has sound-generating organs all over its body. It communicates with others by adjusting the tone and volume of the cries it emits.")
    descriptions.set("makuhita", "It loves to toughen up its body above all else. If you hear quaking rumbles in a cave, it is the sound of MAKUHITA undertaking strenuous training.")
    descriptions.set("hariyama", "It has the habit of challenging others without hesitation to tests of strength. It’s been known to stand on train tracks and stop trains using forearm thrusts.")
    descriptions.set("goldeen", "In the springtime, schools of GOLDEEN can be seen swimming up falls and rivers. It metes out staggering damage with its single horn.")
    descriptions.set("seaking", "It punches holes in boulders on streambeds. This is a clever innovation that prevents its eggs from being attacked or washed away by the current.")
    descriptions.set("magikarp", "Its swimming muscles are weak, so it is easily washed away by currents. In places where water pools, you can see many MAGIKARP deposited there by the flow.")
    descriptions.set("gyarados", "It is an extremely vicious and violent POKéMON. When humans begin to fight, it will appear and burn everything to the ground with intensely hot flames.")
    descriptions.set("azurill", "Its tail, which is packed with nutrition, is very bouncy like a rubber ball. On sunny days they gather at the edge of water and splash about for fun.")
    descriptions.set("marill", "Its body is covered with water-repellent fur. Because of the fur, it can swim through water at high speed without being slowed by the water’s resistance.")
    descriptions.set("azumarill", "It lives in water virtually all day long. Its body color and pattern act as camouflage that makes it tough for enemies to spot in water.")
    descriptions.set("geodude", "It climbs mountain paths using only the power of its arms. Because they look just like boulders lining paths, hikers may step on them without noticing.")
    descriptions.set("graveler", "They descend from mountains by tumbling down steep slopes. They are so brutal, they smash aside obstructing trees and massive boulders with thunderous tackles.")
    descriptions.set("golem", "It is said to live in volcanic craters on mountain peaks. Once a year, it sheds its hide and grows larger. The shed hide crumbles and returns to the soil.")
    descriptions.set("nosepass", "Its body emits a powerful magnetism. It feeds on prey that is pulled in by the force. Its magnetism is stronger in cold seasons.")
    descriptions.set("skitty", "A SKITTY’s adorably cute behavior makes it highly popular. In battle, it makes its tail puff out. It threatens foes with a sharp growl.")
    descriptions.set("delcatty", "Rather than keeping a permanent lair, it habitually seeks comfortable spots and sleeps there. It is nocturnal and becomes active at dusk.")
    descriptions.set("zubat", "While living in pitch-black caverns, their eyes gradually grew shut and deprived them of vision. They use ultrasonic waves to detect obstacles.")
    descriptions.set("golbat", "Its fangs easily puncture even thick animal hide. It loves to feast on the blood of people and POKéMON. It flits about in darkness and strikes from behind.")
    descriptions.set("crobat", "Over the course of evolution, its hind legs turned into wings. By alternately resting its front and rear wings, it can fly all day without having to stop.")
    descriptions.set("tentacool", "Its body is almost entirely composed of water. It ensnares its foe with its two long tentacles, then stabs with the poison stingers at their tips.")
    descriptions.set("tentacruel", "It lives in complex rock formations on the ocean floor and traps prey using its 80 tentacles. Its red orbs glow when it grows excited or agitated.")
    descriptions.set("sableye", "It digs branching holes in caves using its sharp claws in search of food--raw gems. A SABLEYE lurks in darkness and is seen only rarely.")
    descriptions.set("mawile", "Its giant jaws are actually steel horns that transformed. It fools foes into complacency with its adorable gestures, then chomps them with its huge jaws.")
    descriptions.set("aron", "A POKéMON that is clad in steel armor. A new suit of armor is made when it evolves. The old, discarded armor is salvaged as metal for making iron products.")
    descriptions.set("lairon", "When two LAIRON meet in the wild, they fight for territory by bashing into each other with their steel bodies. The sound of their collision carries for miles.")
    descriptions.set("aggron", "Its iron horns grow longer a little at a time. They are used to determine the AGGRON’s age. The gouges in its armor are worn with pride as mementos from battles.")
    descriptions.set("machop", "It continually undertakes strenuous training to master all forms of martial arts. Its strength lets it easily hoist a sumo wrestler onto its shoulders.")
    descriptions.set("machoke", "A belt is worn by a MACHOKE to keep its overwhelming power under control. Because it is so dangerous, no one has ever removed the belt.")
    descriptions.set("machamp", "It is impossible to defend against punches and chops doled out by its four arms. Its fighting spirit flares up when it faces a tough opponent.")
    descriptions.set("meditite", "It continually meditates for hours every day. As a result of rigorous and dedicated yoga training, it has tempered its spiritual power so much it can fly.")
    descriptions.set("medicham", "Through crushingly harsh yoga training, it gained the power to foretell its foe’s actions. It battles with elegant, dance-like movement.")
    descriptions.set("electrike", "It generates electricity using friction from the atmosphere. In seasons with especially arid air, its entire body blazes with violent showers of sparks.")
    descriptions.set("manectric", "Because lightning falls in their vicinities, MANECTRIC were thought to have been born from lightning. In battle, they create thunderclouds.")
    descriptions.set("plusle", "It has the trait of cheering on its fellow POKéMON. By shorting out the electricity it releases from its paws, it creates pom-poms for cheering.")
    descriptions.set("minun", "At a meeting of POKéMON academics, it was announced that simultaneous exposure to electricity from a PLUSLE and MINUN will promote circulation and boost vitality.")
    descriptions.set("magnemite", "The units at its sides are extremely powerful magnets. They generate enough magnetism to draw in iron objects from over 300 feet away.")
    descriptions.set("magneton", "It is actually three MAGNEMITE linked by magnetism. It generates powerful radio waves that raise temperatures by 3.6 degrees F within a 3,300-foot radius.")
    descriptions.set("voltorb", "It bears an uncanny and unexplained resemblance to a POKé BALL. Because it explodes at the slightest shock, even veteran TRAINERS treat it with caution.")
    descriptions.set("electrode", "They appear in great numbers at electric power plants. Because they feed on electricity, they cause massive and chaotic blackouts in nearby cities.")
    descriptions.set("volbeat", "With their taillights lit, VOLBEAT fly in a swarm, drawing geometric designs in the night sky. They move their nests if their pond water becomes dirty.")
    descriptions.set("illumise", "A nocturnal POKéMON that becomes active upon nightfall. It leads a VOLBEAT swarm to draw patterns in the night sky. Over 200 different patterns have been confirmed.")
    descriptions.set("oddish", "This POKéMON grows by absorbing moonlight. During the daytime, it buries itself in the ground, leaving only its leaves exposed to avoid detection by its enemies.")
    descriptions.set("gloom", "A horribly noxious honey drools from its mouth. One whiff of the honey can result in memory loss. Some fans are said to enjoy this overwhelming stink, however.")
    descriptions.set("vileplume", "In seasons when it produces more pollen, the air around a VILEPLUME turns yellow with the powder as it walks. The pollen is highly toxic and causes paralysis.")
    descriptions.set("bellossom", "Its flower petals deepen in color through exposure to sunlight. When cloudy weather persists, it does a dance that is thought to be a ritual for summoning the sun.")
    descriptions.set("doduo", "Even while eating or sleeping, one of the heads remains always vigilant for any sign of danger. When threatened, it flees at over 60 miles per hour.")
    descriptions.set("dodrio", "A peculiar POKéMON species with three heads. It vigorously races across grassy plains even in arid seasons with little rainfall.")
    descriptions.set("roselia", "A ROSELIA that drinks nutritionally rich springwater blooms with lovely flowers. The fragrance of its flowers has the effect of making its foes careless.")
    descriptions.set("gulpin", "This POKéMON’s stomach fluid can even digest scrap iron. In one gulp, it can swallow something that is as large as itself.")
    descriptions.set("swalot", "Its powerful stomach acid is capable of digesting almost anything. The one thing in the whole world a SWALOT can’t digest is its own stomach.")
    descriptions.set("carvanha", "CARVANHA attack ships in swarms, making them sink. Although it is said to be a very vicious POKéMON, it timidly flees as soon as it finds itself alone.")
    descriptions.set("sharpedo", "The vicious and sly gangster of the sea. Its skin is specially textured to minimize drag in water. Its speed tops out at over 75 miles per hour.")
    descriptions.set("wailmer", "While this POKéMON usually lives in the sea, it can survive on land, although not too long. It loses vitality if its body becomes dried out.")
    descriptions.set("wailord", "It breathes through nostrils that it raises above the sea. By inhaling to its maximum capacity, a WAILORD can dive close to 10,000 feet beneath the waves.")
    descriptions.set("numel", "A NUMEL stores boiling magma in the hump on its back. It is a hardy POKéMON that can transport a 220-pound load. It has served humans at work since long ago.")
    descriptions.set("camerupt", "A POKéMON that lives in the crater of a volcano. Every 10 years, the volcanoes on its back erupt violently. Research is under way on the cause of eruption.")
    descriptions.set("slugma", "It is a species of POKéMON that lives in volcanic areas. If its body cools, its skin hardens and immobilizes it. To avoid that, it sleeps near magma.")
    descriptions.set("magcargo", "The shell on its back is made of hardened magma. Tens of thousands of years spent living in volcanic craters have turned MAGCARGO’s bodies into magma.")
    descriptions.set("torkoal", "It battles using energy it gets from burning coal. When loosing smoke from its nostrils, it lets off a sound that is similar to a locomotive’s horn.")
    descriptions.set("grimer", "Born from polluted sludge in the sea, GRIMER’s favorite food is anything filthy. They feed on wastewater pumped out from factories.")
    descriptions.set("muk", "It prefers warm and humid habitats. In the summertime, the toxic substances in its body intensify, making MUK reek like putrid kitchen garbage.")
    descriptions.set("koffing", "Getting up close to a KOFFING will give you a chance to observe, through its thin skin, the toxic gases swirling inside. It blows up at the slightest stimulation.")
    descriptions.set("weezing", "By diluting its toxic gases with a special process, the highest grade of perfume can be extracted. To WEEZING, gases emanating from garbage are the ultimate feast.")
    descriptions.set("spoink", "A POKéMON that manipulates psychic power at will. It doesn’t stop bouncing even when it is asleep. It loves eating mushrooms that grow underground.")
    descriptions.set("grumpig", "It stores power in the black pearls on its forehead. When it uses psychic power, it performs an odd dance step. Its style of dancing became hugely popular overseas.")
    descriptions.set("sandshrew", "When it curls up in a ball, it can make any attack bounce off harmlessly. Its hide has turned tough and solid as a result of living in the desert.")
    descriptions.set("sandslash", "It curls up in a ball to protect itself from enemy attacks. It also curls up to prevent heatstroke during the daytime when temperatures rise sharply.")
    descriptions.set("spinda", "It is distinguished by a pattern of spots that is always different. Its unsteady, tottering walk has the effect of fouling its foe’s aim.")
    descriptions.set("skarmory", "A POKéMON that has a body and wings of steel. People in the past used feathers fallen from SKARMORY to make swords and knives.")
    descriptions.set("trapinch", "Its big jaws crunch through boulders. Because its head is so big, it has a hard time getting back upright if it tips over onto its back.")
    descriptions.set("vibrava", "It looses ultrasonic waves by rubbing its wings together. Since a VIBRAVA’s wings are still in the process of growing, it can only fly short distances.")
    descriptions.set("flygon", "The flapping of its wings sounds like singing. To prevent detection by enemies, it hides itself by flapping up a cloud of desert sand.")
    descriptions.set("cacnea", "CACNEA live in deserts with virtually no rainfall. It battles by swinging its thick, spiked arms. Once a year, a yellow flower blooms.")
    descriptions.set("cacturne", "After spending thousands of years in harsh deserts, its blood transformed into the same substances as sand. It is nocturnal, so it hunts at night.")
    descriptions.set("swablu", "A POKéMON that has wings like cottony clouds. After enduring winter, in which little food is available, SWABLU flocks move closer to towns in the spring.")
    descriptions.set("altaria", "It hums in a beautiful soprano voice. It flies among white clouds in the blue sky. It launches intensely hot fireballs from its mouth.")
    descriptions.set("zangoose", "When it battles, it stands on its hind legs and attacks with its sharply clawed forelegs. Its fur bristles if it encounters any SEVIPER.")
    descriptions.set("seviper", "SEVIPER and ZANGOOSE are eternal rivals. It counters a ZANGOOSE’s dazzling agility with its swordlike tail, which also oozes a horrible poison.")
    descriptions.set("lunatone", "It becomes very active on the night of a full moon. This POKéMON was first discovered 40 years ago at the site of a meteor strike.")
    descriptions.set("solrock", "Solar energy is the source of this POKéMON’s power. On sunny days, groups of SOLROCK line up facing the sun and absorb its light.")
    descriptions.set("barboach", "ts body is covered with a slimy film. The film acts as a barrier to prevent germs in muddy water from entering the BARBOACH’s body.")
    descriptions.set("whiscash", "Mysteriously, it can foretell earthquakes. In the daytime, it sleeps in mud at the bottom of a pond. When it awakens, it continually feeds throughout the night.")
    descriptions.set("corphish", "Once it grips prey with its large pincers, it will never let go, no matter what. It is a hardy POKéMON that can thrive in any environment.")
    descriptions.set("crawdaunt", "A brutish POKéMON that loves to battle. A veteran CRAWDAUNT that has prevailed in hundreds of battles has giant pincers marked with countless scars.")
    descriptions.set("baltoy", "A BALTOY moves by spinning on its single foot. It has been depicted in murals adorning the walls of a once-bustling city in an ancient age.")
    descriptions.set("claydol", "A CLAYDOL sleeps while hovering in midair. Its arms are separate from its body. They are kept floating by the POKéMON’s manipulation of psychic power.")
    descriptions.set("lileep", "It disguises itself as seaweed by making its tentacles sway. Unsuspecting prey that come too close are swallowed whole. It became extinct 100 million years ago.")
    descriptions.set("cradily", "It drags its heavy body along the seafloor. It makes its nest in the shallows of warm seas. CRADILY can be seen on beaches when the tide goes out.")
    descriptions.set("anorith", "It was resurrected from a fossil using the power of science. It swims by undulating the eight wings at its sides. They were feet that adapted to life in the sea.")
    descriptions.set("armaldo", "ARMALDO usually lives on land. However, when it hunts for prey, it dives beneath the ocean. It swims around using its two large wings.")
    descriptions.set("igglybuff", "Its soft and pliable body is very bouncy. When it sings continuously with all its might, its body steadily turns a deepening pink color.")
    descriptions.set("jigglypuff", "Nothing can avoid falling asleep hearing a JIGGLYPUFF’s song. The sound waves of its singing voice match the brain waves of someone in a deep sleep.")
    descriptions.set("wigglytuff", "Its fur is the ultimate in luxuriousness. Sleeping alongside a WIGGLYTUFF is simply divine. Its body expands seemingly without end when it inhales.")
    descriptions.set("feebas", "FEEBAS live in ponds that are heavily infested with weeds. Because of its hopelessly shabby appearance, it seems as if few TRAINERS raise it.")
    descriptions.set("milotic", "It is said to live at the bottom of large lakes. Considered to be the most beautiful of all POKéMON, it has been depicted in paintings and statues.")
    descriptions.set("castform", "It alters its form depending on the weather. Changes in the climate such as the temperature and humidity appear to affect its cellular structure.")
    descriptions.set("staryu", "It gathers with others in the night and makes its red core glow on and off with the twinkling stars. It can regenerate limbs if they are severed from its body.")
    descriptions.set("starmie", "People in ancient times imagined that STARMIE were transformed from the reflections of stars that twinkled on gentle waves at night.")
    descriptions.set("kecleon", "A POKéMON that has the ability to alter its body colors to match its surroundings. A KECLEON reverts to its original colors if it is startled.")
    descriptions.set("shuppet", "This POKéMON roams about deep in the night seeking such negative emotions as grudges and envy. It retreats to its nest when the sun begins to rise.")
    descriptions.set("banette", "An abandoned plush doll became this POKéMON. They are said to live in garbage dumps and wander about in search of the children that threw them away.")
    descriptions.set("duskull", "A glare from its single scarlet eye makes even burly grown-ups freeze in utter fear. It is a nocturnal POKéMON that roams about under the cloak of darkness.")
    descriptions.set("dusclops", "It is thought that its body is hollow with only a spectral ball of fire burning inside. However, no one has been able to confirm this theory as fact.")
    descriptions.set("tropius", "It flies by flapping its broad leaves. The bunch of fruit that grows around its neck is deliciously sweet. In the spring, it scatters pollen from its neck.")
    descriptions.set("chimecho", "They fly about very actively when the hot season arrives. They communicate among themselves using seven different and distinguishing cries.")
    descriptions.set("absol", "It sharply senses even subtle changes in the sky and the land to predict natural disasters. It is a long-lived POKéMON that has a life-span of 100 years.")
    descriptions.set("vulpix", "It can freely control fire, making fiery orbs fly like will-o’-the-wisps. Just before evolution, its six tails grow hot as if on fire.")
    descriptions.set("ninetales", "It has long been said that each of the nine tails embody an enchanted power. A long-lived NINETALES will have fur that shines like gold.")
    descriptions.set("pichu", "It is still inept at retaining electricity. When it is startled, it discharges power accidentally. It gets better at holding power as it grows older.")
    descriptions.set("pikachu", "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.")
    descriptions.set("raichu", "If it stores too much electricity, its behavior turns aggressive. To avoid this, it occasionally discharges excess energy and calms itself down.")
    descriptions.set("psyduck", "When its headache intensifies, it starts using strange powers. However, it has no recollection of its powers, so it always looks befuddled and bewildered.")
    descriptions.set("golduck", "A GOLDUCK is an adept swimmer. It sometimes joins competitive swimmers in training. It uses psychic powers when its forehead shimmers with light.")
    descriptions.set("wynaut", "A WYNAUT loves to eat sweet fruits. It cleverly picks fruits using its earlike arms. They gather in fruit gardens, drawn by the fragrance.")
    descriptions.set("wobbuffet", "Usually docile, a WOBBUFFET strikes back ferociously if its black tail is attacked. It makes its lair in caves where it waits for nightfall.")
    descriptions.set("natu", "It runs up short trees that grow on the savanna to peck at new shoots. A NATU’s eyes look as if they are always observing something.")
    descriptions.set("xatu", "It has the enigmatic power of foreseeing the future. Some people in different lands have long believed that XATU are emissaries from another world.")
    descriptions.set("girafarig", "A GIRAFARIG is an herbivore--it eats grass and tree shoots. While it is eating, its tail makes chewing and swallowing motions as if it were also eating.")
    descriptions.set("phanpy", "PHANPY’s big ears serve as broad fans. When it becomes hot, it flaps the ears busily to cool down. Even the young are very strong.")
    descriptions.set("donphan", "A DONPHAN is so strong it can easily haul a dump truck. Its hide has toughened to a rock-hard state. An ordinary sort of attack won’t even leave a scratch.")
    descriptions.set("pinsir", "Their pincers are strong enough to shatter thick logs. Because they dislike cold, PINSIR burrow and sleep under the ground on chilly nights.")
    descriptions.set("heracross", "They gather in forests seeking the sweet sap of trees. It is completely clad in a steel-hard shell. It is proud of its horn, which it uses to fling foes.")
    descriptions.set("rhyhorn", "Once it starts running, it doesn’t stop. Its tiny brain makes it so stupid that it can’t remember why it started running in the first place.")
    descriptions.set("rhydon", "Its horn, which rotates like a drill, destroys tall buildings with one strike. It stands on its hind legs, and its brain is well developed.")
    descriptions.set("snorunt", "They tend to move about in groups of around five SNORUNT. In snowy regions, it is said that when they are seen late at night, snowfall will arrive by morning.")
    descriptions.set("glalie", "A GLALIE has the power to instantaneously freeze moisture in the atmosphere. A dazzling cloud of diamondlike ice crystals forms around its body.")
    descriptions.set("spheal", "It is completely covered with plushy fur. As a result, it never feels the cold even when it is rolling about on ice floes or diving in the sea.")
    descriptions.set("sealeo", "SEALEO live in herds on ice floes. Using its powerful flippers, it shatters ice. It dives into the sea to hunt prey five times a day.")
    descriptions.set("walrein", "To protect its herd, the leader battles anything that invades its territory, even at the cost of its life. Its tusks may snap off in battle.")
    descriptions.set("clamperl", "A CLAMPERL slams its shell closed on prey to prevent escape. The pearl it creates upon evolution is said to be infused with a mysterious energy.")
    descriptions.set("huntail", "To withstand the crushing pressure of water deep under the sea, its spine is very thick and sturdy. Its tail, which is shaped like a small fish, has eyes that light up.")
    descriptions.set("gorebyss", "A GOREBYSS siphons the body fluids of prey through its thin, tubular mouth. Its light pink body color turns vivid when it finishes feeding.")
    descriptions.set("relicanth", "A POKéMON that was once believed to have been extinct. The species has not changed its form for 100 million years. It walks on the seafloor using its pectoral fins.")
    descriptions.set("corsola", "CORSOLA live in warm southern seas. If the sea becomes polluted, the beautiful coral stalks become discolored and crumble away in tatters.")
    descriptions.set("chinchou", "When it senses danger, it discharges positive and negative electricity from its two antennae. It lives in depths beyond sunlight’s reach.")
    descriptions.set("lanturn", "The light-emitting orbs on its back are very bright. They are formed from a part of its dorsal fin. This POKéMON illuminates the inky darkness of deep seas.")
    descriptions.set("luvdisc", "LUVDISC make the branches of CORSOLA their nests. There is a custom from long ago of giving a LUVDISC as a gift to express one’s feelings of love.")
    descriptions.set("horsea", "By cleverly flicking the fins on its back side to side, it moves in any direction while facing forward. It spits ink to escape if it senses danger.")
    descriptions.set("seadra", "The poisonous barbs all over its body are highly valued as ingredients for making traditional herbal medicine. It shows no mercy to anything approaching its nest.")
    descriptions.set("kingdra", "It sleeps quietly, deep on the seafloor. When it comes up to the surface, it creates a huge whirlpool that can swallow even ships.")
    descriptions.set("bagon", "Although it is small, this POKéMON is very powerful because its body is a bundle of muscles. It launches head-butts with its ironlike skull.")
    descriptions.set("shelgon", "It hardly eats while it awaits evolution. It becomes hardier by enduring hunger. Its shell peels off the instant it begins to evolve.")
    descriptions.set("salamence", "After many long years, its cellular structure underwent a sudden mutation to grow wings. When angered, it loses all thought and rampages out of control.")
    descriptions.set("beldum", "When BELDUM gather in a swarm, they move in perfect unison as if they were but one POKéMON. They communicate with each other using brain waves.")
    descriptions.set("metang", "The claws tipping its arms pack the destructive power to tear through thick iron sheets as if they were silk. It flies at over 60 miles per hour.")
    descriptions.set("metagross", "METAGROSS has four brains that are joined by a complex neural network. As a result of integration, this POKéMON is smarter than a supercomputer.")
    descriptions.set("regirock", "A POKéMON that is made entirely of rocks and boulders. If parts of its body chip off in battle, REGIROCK repairs itself by adding new rocks.")
    descriptions.set("regice", "Its entire body is made of Antarctic ice. After extensive studies, researchers believe the ice was formed during an ice age.")
    descriptions.set("registeel", "Its body is harder than any other kind of metal. The body metal is composed of a mysterious substance. Not only is it hard, it shrinks and stretches flexibly.")
    descriptions.set("latias", "They make a small herd of only several members. They rarely make contact with people or other POKéMON. They disappear if they sense enemies.")
    descriptions.set("latios", "Even in hiding, it can detect the locations of others and sense their emotions since it has telepathy. Its intelligence allows it to understand human languages.")
    descriptions.set("kyogre", "KYOGRE has appeared in mythology as the creator of the sea. After long years of feuding with GROUDON, it took to sleep at the bottom of the sea.")
    descriptions.set("groudon", "GROUDON has appeared in mythology as the creator of the land. It sleeps in magma underground and is said to make volcanoes erupt on awakening.")
    descriptions.set("rayquaza", "A POKéMON that flies endlessly in the ozone layer. It is said it would descend to the ground if KYOGRE and GROUDON were to fight.")
    descriptions.set("jirachi", "JIRACHI is said to make wishes come true. While it sleeps, a tough crystalline shell envelops the body to protect it from enemies.")
    descriptions.set("deoxys", "A POKéMON that mutated from an extraterrestrial virus exposed to a laser beam. Its body is configured for superior agility and speed.")
    return descriptions.get(poke)
}

export function admin() {
    let pokedex = [
        "treecko",
        "grovyle",
        "sceptile",
        "torchic",
        "combusken",
        "blaziken",
        "mudkip",
        "marshtomp",
        "swampert",
        "poochyena",
        "mightyena",
        "zigzagoon",
        "linoone",
        "wurmple",
        "silcoon",
        "beautifly",
        "cascoon",
        "dustox",
        "lotad",
        "lombre",
        "ludicolo",
        "seedot",
        "nuzleaf",
        "shiftry",
        "taillow",
        "swellow",
        "wingull",
        "pelipper",
        "ralts",
        "kirlia",
        "gardevoir",
        "surskit",
        "masquerain",
        "shroomish",
        "breloom",
        "slakoth",
        "vigoroth",
        "slaking",
        "abra",
        "kadabra",
        "alakazam",
        "nincada",
        "ninjask",
        "shedinja",
        "whismur",
        "loudred",
        "exploud",
        "makuhita",
        "hariyama",
        "goldeen",
        "seaking",
        "magikarp",
        "gyarados",
        "azurill",
        "marill",
        "azumarill",
        "geodude",
        "graveler",
        "golem",
        "nosepass",
        "skitty",
        "delcatty",
        "zubat",
        "golbat",
        "crobat",
        "tentacool",
        "tentacruel",
        "sableye",
        "mawile",
        "aron",
        "lairon",
        "aggron",
        "machop",
        "machoke",
        "machamp",
        "meditite",
        "medicham",
        "electrike",
        "manectric",
        "plusle",
        "minun",
        "magnemite",
        "magneton",
        "voltorb",
        "electrode",
        "volbeat",
        "illumise",
        "oddish",
        "gloom",
        "vileplume",
        "bellossom",
        "doduo",
        "dodrio",
        "roselia",
        "gulpin",
        "swalot",
        "carvanha",
        "sharpedo",
        "wailmer",
        "wailord",
        "numel",
        "camerupt",
        "slugma",
        "magcargo",
        "torkoal",
        "grimer",
        "muk",
        "koffing",
        "weezing",
        "spoink",
        "grumpig",
        "sandshrew",
        "sandslash",
        "spinda",
        "skarmory",
        "trapinch",
        "vibrava",
        "flygon",
        "cacnea",
        "cacturne",
        "swablu",
        "altaria",
        "zangoose",
        "seviper",
        "lunatone",
        "solrock",
        "barboach",
        "whiscash",
        "corphish",
        "crawdaunt",
        "baltoy",
        "claydol",
        "lileep",
        "cradily",
        "anorith",
        "armaldo",
        "igglybuff",
        "jigglypuff",
        "wigglytuff",
        "feebas",
        "milotic",
        "castform",
        "staryu",
        "starmie",
        "kecleon",
        "shuppet",
        "banette",
        "duskull",
        "dusclops",
        "tropius",
        "chimecho",
        "absol",
        "vulpix",
        "ninetales",
        "pichu",
        "pikachu",
        "raichu",
        "psyduck",
        "golduck",
        "wynaut",
        "wobbuffet",
        "natu",
        "xatu",
        "girafarig",
        "phanpy",
        "donphan",
        "pinsir",
        "heracross",
        "rhyhorn",
        "rhydon",
        "snorunt",
        "glalie",
        "spheal",
        "sealeo",
        "walrein",
        "clamperl",
        "huntail",
        "gorebyss",
        "relicanth",
        "corsola",
        "chinchou",
        "lanturn",
        "luvdisc",
        "horsea",
        "seadra",
        "kingdra",
        "bagon",
        "shelgon",
        "salamence",
        "beldum",
        "metang",
        "metagross",
        "regirock",
        "regice",
        "registeel",
        "latias",
        "latios",
        "kyogre",
        "groudon",
        "rayquaza",
        "jirachi",
        "deoxys"]
        pokedex.forEach(x => 
            Axios.post("https://pokemon-server-zzdv.onrender.com/seen-pokemon", {
                username: "admin",
                pokemon: x
              }).then((response) => {
                console.log('pepelaugh')

            })
            )
        
}
